const techApi = [
    {
        id:1,
        Name:'imagesa/react.png',
        width:'50px'
    }
    ,
    {
        id:2,
        Name:'imagesa/php.png',
        width:'50px'
    },
    {
        id:3,
        Name:'imagesa/nodsa.png',
        width:'50px'
    },
    {
        id:4,
        Name:'imagesa/laravel.png',
        width:'60px'
    },
    {
        id:5,
        Name:'imagesa/mag2.png',
        width:'70px'
    },
    {
        id:6,
        Name:'imagesa/shopi2.png',
        width:'60px'
    },
    {
        id:7,
        Name:'imagesa/kub.png',
        width:'110px'
    }
]

export default techApi;